#!/bin/sh /etc/rc.common

START=91

NAME=udp2raw-client
PROG=/usr/bin/udp2raw-client
USE_PROCD=1

start_instance() {
  local enable
  local listen_addr
  local listen_port
  local server_addr
  local server_port
  local password
  local raw_mode
  local cipher_mode
  local auth_mode
  local fix_gro

	config_get_bool enable $1 enable
	[ "$enable" = 1 ] || return 0

  config_get listen_addr "$1" listen_addr
  config_get listen_port "$1" listen_port
  config_get server_addr "$1" server_addr
  config_get server_port "$1" server_port
  config_get key "$1" key
  config_get raw_mode "$1" raw_mode
  config_get cipher_mode "$1" cipher_mode
  config_get auth_mode "$1" auth_mode
  config_get fix_gro "$1" fix_gro

  procd_open_instance
  procd_set_param respawn
  procd_set_param command $PROG $listen_addr $listen_port $server_addr $server_port $key $raw_mode $cipher_mode $auth_mode $fix_gro
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}

service_triggers() {
  procd_add_reload_trigger $NAME
}

start_service() {
  config_load $NAME
  config_foreach start_instance udp2raw-client
}

stop_service() {
	config_load $NAME
  pidof udp2raw && kill -SIGINT `pidof udp2raw`
}

reload_service() {
	stop
	start
}